### PR TITLE
Successfully Integrated Date Picker

### PR DESCRIPTION
**Pull request by Arnab55555**
Good evening sir, I have successfully integrated a Date Picker in the dashboard.

### CODE REVIEW

**Comment by mrrishimeena** [comment]
@Arnab55555 Let me review it, and then I will merge it.

**Comment by mrrishimeena** [comment]
@Arnab55555 Everything looks good so far. Can you also add a time-picker? We need to include both a date-picker and a time-picker.

**Review by Arnab55555 — COMMENTED** [review]
Added Time Picker

**Comment by Arnab55555** [comment]
Sir I have added the Time Picker as requested

**Comment by mrrishimeena** [comment]
@Arnab55555 Everything looks good after testing.

**Pull request merged**
