### PR TITLE
fix: improve error handling for controllers

### LINKED ISSUE #82: Avoid returning custom error messages from the API
Avoid returning custom error messages from the API. Instead, return the error message provided by the storage module, e.g., err.message.

### PR DESCRIPTION
**Pull request by oscarArismendi**
## Related issues
- Closes #82 

## Summary
I have updated the error handling to implement `error.message` as discussed. However, I've encountered three types of test failures:

1. **Formatting Issue**: 
   - **Test Expectation**: `"message": "An unexpected error occurred"`
   - **Current Response**: `"message": "Unexpected error"`
   - **Observation**: The response is correct but does not match the expected format. Adjusting this would require changes beyond the three files specified. Should we create a new issue for this or update it here?
   <p align="center">
      
      Test fails due to incorrect formatting
   </p>

2. **Precision Issue**:
   - **Test Expectation**: `"message": "An unexpected error occurred"`
   - **Current Response**: Error message is correct, but the test expects a more specific message. This may be due to previous tests being less flexible. Should we update the test to match the current implementation?
   <p align="center">
      
      Test fails due to specificity
   </p>

3. **Vague Error Message**:
   - **Test Expectation**: `"message": "An unexpected error occurred"`
   - **Current Response**: `"message": "Something went wrong"`
   - **Observation**: The response is too vague. Updating this to match the test expectation would require changes outside of the current scope. Should we address this in a separate issue?
   <p align="center">
      
      Test fails due to vague error message
   </p>

## Conclusion
I’ve tried to address the issues but encountered several test failures due to differing expectations. I’m seeking feedback on whether to update the tests or adjust the implementation. Additionally, please guide me if there are other files or areas that you would like me to modify to resolve these issues. Your advice on the best approach to ensure alignment with expected outcomes without impacting existing functionality would be greatly appreciated.

### CODE REVIEW

**Comment by mrrishimeena** [comment]
@oscarArismendi If you're able to modify the test cases, that would be great. Otherwise, we'll create a separate issue for it and handle the test case adjustments there.

**Comment by oscarArismendi** [comment]
Hey @mrrishimeena,
I’ll work on fixing the test cases then. I’ll update them in this PR. If there’s anything specific I should keep in mind, just let me know!

**Comment by oscarArismendi** [comment]
I have refactored the tests to the best of my ability, ensuring they align with the current logic and error handling. However, I’m open to any suggestions or further improvements you may see fit.

Additionally, I’ve included an image below showing that all tests are passing:
<p align="center">
   
</p>

**Comment by mrrishimeena** [comment]
@oscarArismendi Thanks, Let me review it, and then I will merge it.

**Comment by mrrishimeena** [comment]
@oscarArismendi Your approach is good, but there’s one issue: what if the error object doesn’t have a message property?

```
const error = { /* no message property */ };
const message = error ? error.message : 'An unexpected error occurred';
console.log(message); // Output: undefined

```

**Comment by oscarArismendi** [comment]
Mmmm I get it, don't worry I will fix it

**Comment by oscarArismendi** [comment]
@mrrishimeena The changes are all set! If you have any other suggestions or requests, just let me know!

**Comment by mrrishimeena** [comment]
@oscarArismendi Everything looks good.

**Comment by mrrishimeena** [comment]
@SaiKumar2121 The error handling message has been fixed by @oscarArismendi. Kindly proceed with the final testing before publishing it to NPM.

**Pull request merged**
